version: '3.8'
services:
   ts-mod-api:
      build:
         context: .
         dockerfile: ./Dockerfile
      ports:
         - 8080:8080
      environment:
         - SPRING_PROFILES_ACTIVE=demo
         - SPRINGDOC_SWAGGER_UI_URL=http://nfdi4chemdemo21.service.tib.eu:8080
      restart: always