version: '3.8'
services:
   ts-mod-api:
      build:
         context: .
         dockerfile: ./Dockerfile
      ports:
         - 8080:8080
      environment:
         - SPRING_PROFILES_ACTIVE=demo
      restart: always