spring:
  application:
    name: ts-mod-api
  profiles:
    active: demo

  # Swagger UI configurations via springdoc
springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs
    path: /swagger-ui.html

server:
  port: 8080
  forward-headers-strategy: framework
  #url: "https://service.tib.eu/terminology/mod/api"
  servlet:
    context: /mod

logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG