spring:
  application:
    name: ts-mod-api
  profiles:
    active: demo

  # Swagger UI configurations via springdoc
springdoc:
  swagger-ui:
    enabled: true
    url: /v3/api-docs

server:
  port: 8080
  forward-headers-strategy: framework
  url: "https://service.tib.eu/terminology/mod/api"

logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG