spring:
  application:
    name: ts-mod-api
  profiles:
    active: demo

  # Swagger UI configuration via springdoc
springdoc:
  swagger-ui:
    enabled: true
    url: http://nfdi4chemdemo21.service.tib.eu:8080
    path: /swagger-ui.html

server:
  port: 8080
  forward-headers-strategy: native
  url: "http://nfdi4chemdemo21.service.tib.eu:8080"

logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG