spring:
  application:
    name: ts-mod-api
  profiles:
    active: demo

  # Swagger UI configuration via springdoc
  doc:
    swagger-ui:
      path: /swagger-ui.html

server:
  port: 8080
  forward-headers-strategy: framework

logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG