spring:
  application:
    name: ts-mod-api
  profiles:
    active: demo

  # Swagger UI configurations via springdoc
  doc:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

server:
  port: 8080
  forward-headers-strategy: native
  url: "http://nfdi4chemdemo21.service.tib.eu:8080"

logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG