spring:
  application:
    name: ts-mod-api
  profiles:
    active: demo

  # Swagger UI configurations via springdoc
  doc:
    swagger-ui:
      enabled: true
      url: /v3/api-docs
      path: /swagger-ui/index.html

server:
  port: 8080
  forward-headers-strategy: native
  url: "https://service.tib.eu/terminology/mod-api/"

logging:
  level:
    org:
      springframework:
        core:
          env: DEBUG