mappings:
  modAttributes:
    semanticArtefactId:
      - jsonPath: "$.ontologyId"
        priority: 1
    contactPoint:
      - jsonPath: "$.config.mailingList"
        keys: ["@id", "@type", "vcard:fn", "vcard:nickname"]
        type: 'vcard:Kind'
        priority: 1
    creator:
      - jsonPath: "$.config.subject"
        type: 'foaf:agent'
        keys: ["@id", "@type"]
        priority: 1
    description:
      - jsonPath: "$.config.description"
        keys: ["@id", "@type"]
        type: 'dcterms:identifier'
        priority: 1
    isReferencedBy:
      - jsonPath: "$.config['Is Referenced By']"
        keys: ["@id", "@type"]
        type: 'dcterms:isReferencedBy'
        priority: 1