package com.tib.ts.mod.entities.enums;

/**
 *@author Deepan Anbalagan
 *@email deepan.anbalagan@tib.eu
 *TIB-Leibniz Information Center for Science and Technology
*/

public enum ActionType {
	ONTOLOGIES,
	ONTOLOGIES_BY_ONTOLOGY_IRI,
	ONTOLOGY_BY_ONTOLOGY_ID,
	ENTITIES_BY_ONTOLOGY_ID,
	ENTITIES_BY_ONTOLOGY_ID_AND_IRI,
	CLASSES_BY_ONTOLOGY_ID,
	CLASSES_BY_ONTOLOGY_ID_AND_IRI,
	PROPERTIES_BY_ONTOLOGY_ID,
	PROPERTIES_BY_ONTOLOGY_ID_AND_IRI,
	INDIVIDUALS_BY_ONTOLOGY_ID,
	INDIVIDUALS_BY_ONTOLOGY_ID_AND_IRI,
	V1Search,
	CATALOG
}
